apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "reops-events"
  namespace: "team-researchops"
  labels:
    "team": "team-researchops"
spec:
  image: "{{image}}"
  port: 8080
  liveness:
    path: "internal/isalive"
  readiness:
    path: "internal/isready"
  replicas:
    min: 2
    max: 2
  prometheus:
    enabled: false
    path: "/internal/metrics"
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
  ingresses:
    - https://reops-events.intern.dev.nav.no/
  env:
    - name: GCS_BATCH_SIZE
      value: "5000"
    - name: GCS_MAX_INTERVAL_SECONDS
      value: "10"
    - name: GCS_BUCKET_PREFIX
      value: "gs://{{ bucket.name }}/events"
  gcp:
    buckets:
      - name: "{{ bucket.name }}"
        retentionPeriodDays: 3
        publicAccessPrevention: true
        lifecycleCondition:
          age: 7 # days