apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: dp-events-tabell
  namespace: team-researchops
  labels:
    team: team-researchops
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: absent
spec:
  resourceID: dp-events-tabell
  datasetRef:
    external: dataprodukt
  description: "BigQuery tabell som leser Parquet filer fra GCS"
  externalDataConfiguration:
    sourceFormat: PARQUET
    sourceUris:
      - gs://{{ bucket.name}}/events/*.parquet
    autodetect: true
    parquetOptions:
      enableListInference: true
      enumAsString: false
    hivePartitioningOptions:
      mode: AUTO
      requirePartitionFilter: false
      sourceUriPrefix: gs://{{ bucket.name }}/events/

