apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: reops-events-bucket-viewer
  labels:
    team: team-researchops
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: "{{project}}"
    cnrm.cloud.google.com/state-into-spec: absent
spec:
  member: "serviceAccount:nais-sa-cnrm@{{project}}.iam.gserviceaccount.com"
  role: roles/storage.objectViewer
  resourceRef:
    kind: StorageBucket
    name: reops-events-bucket
