name: Build and deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

env:
  dataset: events

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: "write" # For å submitte dependency graph
      checks: "write"
      pull-requests: "write"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/wrapper-validation@v4
      - uses: gradle/actions/setup-gradle@v4
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          dependency-graph: generate-and-submit
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
      - run: ./gradlew installDist #--configuration-cache build

      - name: Publish results (unit test)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          junit_files: "**/build/test-results/test/TEST-*.xml"

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: team-researchops
          tag: ${{ github.sha }}
          dockerfile: app/Dockerfile
          docker_context: app
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      digest: ${{ steps.docker-build-push.outputs.digest }}

  deploy-dataset:
    name: Deploy BigQuery dataset
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev-gcp
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/cnrm/dataset.yaml #,.nais/cnrm/permission.yaml
          VAR: project=team-researchops-dev-4396,dataset=${{ env.dataset }}
          PRINT_PAYLOAD: true

  deploy-views:
    name: Deploy BigQuery views
    needs: [ deploy-dataset ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev-gcp
    permissions:
      id-token: write
    strategy:
      matrix:
        table: [ events, events-attributes ]
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "SCHEMA<<EOF" >> "$GITHUB_ENV"
          cat .nais/views/${{matrix.table}}.schema.yaml >> $GITHUB_ENV
          echo "EOF" >> "$GITHUB_ENV"
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/views/parquet-table.yaml
          VAR: project=team-researchops-dev-4396,dataset=${{ env.dataset }},table=${{ matrix.table }},schema=${{ env.SCHEMA }}
          VARS: .nais/vars-dev.yaml
          PRINT_PAYLOAD: true

  deploy-dev:
    name: Deploy to dev
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev-gcp
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/vars-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
          PRINT_PAYLOAD: true